Feature/feature crud remaining
Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice pull request #25
Opened 2020-04-22 09:12 UTC by oricat8

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 111
           

Complexity increasing per file
==============================
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqTrainingRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalAverageRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetWeekTrainingRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqWashRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  1
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/KcalService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashService.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageService.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingService.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494&bid=17704389)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java
> +import org.springframework.web.bind.annotation.*;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Using the '.*' form of import should be avoided - org.springframework.web.bind.annotation.*.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java
> +    public void createFreqTraining(@PathVariable String owner, @PathVariable String petName, @PathVariable String petDate,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 122).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java
> +            doThrow(DatabaseAccessException.class).when(kcalAverageDao).getAllKcalAverage(any(String.class), isA(String.class));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 128).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqTrainingRestControllerTest.java
> +        willDoNothing().given(service).createFreqTraining(anyString(), anyString(), anyString(), isA(FreqTrainingEntity.class));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 128).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/service/FreqWashServiceImpl.java
> +    public FreqWashEntity getFreqWashByDate(String owner, String petName, String petDate) throws DatabaseAccessException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 122).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +        value = 9.0 / 2.0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['9.0' is a magic number.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java
> +            doThrow(DatabaseAccessException.class).when(freqTrainingDao).getFreqTrainingByDate(any(String.class), any(String.class),
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 132).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java
> +    public void updateKcalAverage(@PathVariable String owner, @PathVariable String petName, @PathVariable String petDate,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 121).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java
> +        value = 9.0 / 2.0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['9.0' is a magic number.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalAverageRestControllerTest.java
> +        willDoNothing().given(service).createKcalAverage(anyString(), anyString(), anyString(), isA(KcalAverageEntity.class));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 126).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetWeekTrainingRestControllerTest.java
> +        willDoNothing().given(service).createWeekTraining(anyString(), anyString(), anyString(), isA(WeekTrainingEntity.class));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 128).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/service/FreqTrainingServiceImpl.java
> +    public FreqTrainingEntity getFreqTrainingByDate(String owner, String petName, String petDate) throws DatabaseAccessException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 130).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +        value = 9.0 / 2.0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['9.0' is a magic number.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +import com.google.cloud.firestore.*;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Using the '.*' form of import should be avoided - com.google.cloud.firestore.*.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +public class KcalAverageDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java
> +    private void getAllFreqTrainingsOfAPetFromDatabase(CollectionReference freqTrainingsRef, List<Map<String, Object>> externalList)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 132).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +    public void shouldThrowDatabaseAccessExceptionWhenGetAllWeekTrainingsBetweenFromDatabaseReceivesInterruptedException() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 124).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java
> +public class FreqTrainingDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java
> +    public void updateWeekTraining(@PathVariable String owner, @PathVariable String petName, @PathVariable String petDate,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 122).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java
> +    public List<Map<String, Object>> getAllFreqTrainingsBetween(@PathVariable String owner, @PathVariable String petName,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 121).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:14 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDao.java
> +    WeekTrainingEntity getWeekTrainingByDate(String owner, String petName, String petDate) throws DatabaseAccessException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Line is longer than 120 characters (found 122).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:47 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 41
           

Complexity increasing per file
==============================
- src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqWashRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalAverageRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetWeekTrainingRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqTrainingRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashServiceImpl.java  1
         

Clones added
============
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/dao/KcalDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingService.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashService.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494&bid=17704389)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +public class KcalAverageDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +        value = 9.0 / 2.0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['9.0' is a magic number.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java
> +        value = 9.0 / 2.0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['9.0' is a magic number.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +import com.google.cloud.firestore.DocumentSnapshot;import org.junit.jupiter.api.BeforeAll;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [';' is not followed by whitespace.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java
> +import org.springframework.web.bind.annotation.*;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Using the '.*' form of import should be avoided - org.springframework.web.bind.annotation.*.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +public class KcalDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java
> +import org.springframework.web.bind.annotation.*;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Using the '.*' form of import should be avoided - org.springframework.web.bind.annotation.*.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +public class FreqWashDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +import com.google.cloud.firestore.DocumentSnapshot;import org.junit.jupiter.api.BeforeAll;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Only one statement per line allowed.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java
> +import com.google.cloud.firestore.DocumentSnapshot;import org.pesmypetcare.webservice.entity.KcalAverageEntity;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [';' is not followed by whitespace.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +        value = 9.0 / 2.0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['9.0' is a magic number.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java
> +public class WeekTrainingServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java
> +public class KcalAverageServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +        value = 9.0 / 2.0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['9.0' is a magic number.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 09:48 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java
> +import org.springframework.web.bind.annotation.*;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Using the '.*' form of import should be avoided - org.springframework.web.bind.annotation.*.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:00 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 26
           

Complexity increasing per file
==============================
- src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqTrainingRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetWeekTrainingRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalAverageRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqWashRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageServiceImpl.java  1
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/KcalService.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashService.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingService.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDao.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494&bid=17704389)

2020-04-22 10:00 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java
> +public class FreqTrainingDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:00 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:00 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:00 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +public class WeekTrainingDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java
> +        value = 9.0 / 2.0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['9.0' is a magic number.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +public class FreqWashDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java
> +public class KcalServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +public class KcalDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java
> +public class FreqWashServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +public class KcalAverageDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java
> +public class FreqTrainingServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java
> +public class WeekTrainingServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:01 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:04 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 25
           

Complexity increasing per file
==============================
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/service/KcalServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqTrainingRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalAverageRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqWashRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetWeekTrainingRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageServiceImpl.java  1
         

Clones added
============
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalService.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashService.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  42
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494&bid=17704389)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java
> +public class WeekTrainingServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +public class KcalAverageDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java
> +public class KcalServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java
> +public class FreqTrainingServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java
> +public class FreqWashServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +public class FreqWashDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +public class WeekTrainingDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java
> +public class FreqTrainingDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +public class KcalDaoTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java
> +public class KcalAverageServiceTest {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This class has too many methods, consider refactoring it.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 10:05 UTC, santidrj commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +    @Test
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 16:16 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalAverageRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java  5
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetWeekTrainingRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqTrainingRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqWashRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalRestControllerTest.java  1
         

Clones added
============
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/FreqWashService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageService.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/dao/KcalDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalService.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingService.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  42
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494&bid=17704389)

2020-04-22 16:16 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 16:16 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 16:16 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 16:16 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java
> +                Map<String, Object> internalList = new HashMap<>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating new objects inside loops](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494)

2020-04-22 17:12 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqTrainingRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalAverageRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqWashRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetWeekTrainingRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java  1
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingService.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/FreqWashService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/KcalService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDao.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494&bid=17704389)

2020-04-22 19:51 UTC, AlvarTB requested changes

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java
> +     * @param freqTrainingEntity The parameters of freqTraining
You forgot to add petDate as a @param.

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java
> +     * @param petName Name of the pet
You forgot to add petDate in the comments.

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java
> +     * Gets the data from all the meals eaten by the pet between the initial and final date not including them.
I am being a bit picky here, but the description isn't it about the wash frequencies instead of meals?

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java
> +     * @param petName Name of the pet
You forgot petDate here.

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java
> +     * Gets the data from all the meals eaten by the pet between the initial and final date not including them.
Watch out, aren't you talking about KcalAverages instead of meals?

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java
> +     * @param owner Username of the owner of the pet
Forgot to add petDate

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java
> +     * @param owner Username of the owner of the pet
Forgot to add petDate in comments.

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDao.java
> +     * Gets the data from all the meals eaten by the pet between the initial and final date not including them.
Shouldn't it be of the freqTrainings?

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoImpl.java
> +
You forgot to add descriptions for the methods of this file, but I am not sure if that's too important.

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/dao/FreqWashDaoImpl.java
> +     * Return the freqWash collection of one pet.
You should probably add descriptions for the methods of this file, too.

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDaoImpl.java
> +    }
Yo should probably add descriptions for the methods of this file, too.

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/dao/KcalDaoImpl.java
> +        kcalRef.update("kcalValue", value);
You should probably add the rest of the descriptions for this file.

2020-04-22 19:51 UTC, AlvarTB commented on src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java
> +
You should add the rest of the descriptions for these methods in this file.

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +        assertEquals(freqWashList, list, "Should return a List containing all meals Data");
You meant... wash data?

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java
> +        assertEquals(freqWashList, list, "Should return a List containing all meals between two dates");
You meant... wash data?

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +        assertSame(kcalAverageEntity, meal, "Should return Meal Entity");
I think it should return KcalAverageEntity, right?

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +        assertEquals(kcalAverageList, list, "Should return a List containing all meals Data");
All Kcal data, right?

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java
> +        assertEquals(kcalAverageList, list, "Should return a List containing all meals between two dates");
All Kcal's, right?

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +        assertSame(kcalEntity, meal, "Should return Meal Entity");
"Should return kcal entity"

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +        assertEquals(kcalList, list, "Should return a List containing all meals Data");
"List containing all kcal data"

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java
> +        assertEquals(kcalList, list, "Should return a List containing all meals between two dates");
"...all kcal's..."

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +        assertSame(weekTrainingEntity, meal, "Should return Meal Entity");
"...week Training Entity"

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +        assertEquals(weekTrainingList, list, "Should return a List containing all meals Data");
"...all week trainings data"

2020-04-22 19:51 UTC, AlvarTB commented on src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java
> +        assertEquals(weekTrainingList, list, "Should return a List containing all meals between two dates");
"...all week trainings..." (?)

2020-04-23 12:23 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/test/java/org/pesmypetcare/webservice/service/KcalAverageServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqTrainingServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqWashRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/service/KcalServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageServiceImpl.java  1
- src/test/java/org/pesmypetcare/webservice/service/WeekTrainingServiceTest.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetKcalAverageRestControllerTest.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetFreqTrainingRestControllerTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalRestController.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoImpl.java  5
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  1
- src/test/java/org/pesmypetcare/webservice/service/FreqWashServiceTest.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/WeekTrainingRestController.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/FreqWashRestController.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingServiceImpl.java  1
- src/main/java/org/pesmypetcare/webservice/controller/petmanager/KcalAverageRestController.java  1
- src/test/java/org/pesmypetcare/webservice/controller/petmanager/PetWeekTrainingRestControllerTest.java  1
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/WeekTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalAverageDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/FreqTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/dao/FreqWashDao.java  1
- src/main/java/org/pesmypetcare/webservice/dao/KcalDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/WeekTrainingDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/KcalService.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqTrainingService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/FreqTrainingDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/FreqWashService.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalAverageDaoTest.java  42
- src/test/java/org/pesmypetcare/webservice/dao/FreqWashDaoTest.java  42
- src/main/java/org/pesmypetcare/webservice/service/KcalAverageService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/WeekTrainingDao.java  1
- src/test/java/org/pesmypetcare/webservice/dao/KcalDaoTest.java  42
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5400494&bid=17704389)

2020-04-23 12:55 UTC, AlvarTB approved these changes
No issues here. Good job!

2020-04-23 13:43 UTC, santidrj approved these changes
👍

2020-04-23 13:45 UTC, merged