Feature/feature pet attributes refactor
Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice pull request #43
Opened 2020-05-04 21:37 UTC by marclll

2020-05-04 21:38 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/entity/PetEntity.java
> +                throw new IllegalArgumentException("Request body does not have a correct format");
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String "Request body does not have a correct format" appears 4 times in the file.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-04 21:38 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Coverage decreased per file
===========================
- src/main/java/org/pesmypetcare/webservice/builders/Path.java  -2
         

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-04 21:38 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/entity/PetEntity.java
> +            if (body.size() != 1 || !body.containsKey("value")) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String "value" appears 2 times in the file.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-04 21:38 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/entity/PetEntity.java
> +    public static void checkKeyAndBody(String field, String key, Map<String, Object> body) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [NCSS for this method is 16 (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-04 21:38 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/entity/PetEntity.java
> +    public PetEntity(GenderType gender, String breed, String birth, String pathologies, String needs,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [More than 5 parameters (found 8).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-04 21:38 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/entity/PetEntity.java
> +    public static void checkKeyAndBody(String field, String key, Map<String, Object> body) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method length is 17 lines (max allowed is 15).](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-04 21:38 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/entity/PetEntity.java
> +            if (body.size() != 2 || !body.containsKey("kcal") || !body.containsKey("mealName")) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String "mealName" appears 2 times in the file.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-04 21:38 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/builders/Path.java
> +    /**
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [First sentence should end with a period.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-04 21:40 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Coverage decreased per file
===========================
- src/main/java/org/pesmypetcare/webservice/builders/Path.java  -2
         

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-04 21:40 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/builders/Path.java
> +    /**
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [First sentence should end with a period.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-04 23:03 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Coverage decreased per file
===========================
- src/main/java/org/pesmypetcare/webservice/builders/Path.java  -2
         

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-04 23:03 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/builders/Path.java
> +    /**
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [First sentence should end with a period.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-05 05:54 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- src/main/java/org/pesmypetcare/webservice/builders/Path.java  -2
         

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-05 08:32 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- src/main/java/org/pesmypetcare/webservice/builders/Path.java  -2
         

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-05 09:14 UTC, oricat8 approved these changes
Ok!

2020-05-05 09:19 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-05 09:58 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/PetRestController.java
> +        PetEntity.checkSimpleFieldAndValues(field, valueMap.get("value"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String "value" appears 2 times in the file.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-05 09:58 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-05 10:47 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-05 10:47 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/PetRestController.java
> +        PetEntity.checkSimpleFieldAndValues(field, valueMap.get("value"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String "value" appears 2 times in the file.](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160)

2020-05-05 16:07 UTC, santidrj requested changes
There are a couple of things that need to be revised

2020-05-05 16:07 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/controller/petmanager/PetRestController.java
> +     * @return The PetEntity of the owner data
Shouldn't it  be 'pet data' instead of 'owner data'?

2020-05-05 16:07 UTC, santidrj commented on src/main/java/org/pesmypetcare/webservice/service/PetService.java
> +     * @return The PetEntity of the owner data
Shouldn't it be 'pet data' instead of 'owner data'?

2020-05-05 17:54 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-05 18:00 UTC, santidrj commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- src/main/java/org/pesmypetcare/webservice/builders/Path.java  -2
         

Complexity decreasing per file
==============================
+ src/test/java/org/pesmypetcare/webservice/dao/PetDaoTest.java  -2
         

Clones added
============
- src/main/java/org/pesmypetcare/webservice/service/PetService.java  1
- src/main/java/org/pesmypetcare/webservice/dao/PetDao.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care-Webservice/pullRequest?prid=5469160&bid=17924220)

2020-05-05 18:39 UTC, santidrj approved these changes
:+1:

2020-05-05 19:14 UTC, merged